
build:
  version: "3.0"

loans:
  message: "Welcome to Zeroday loanaccounts related Produc APIs "
  contactDetails:
    name: "Siva - Product Owner"
    email: "srivardhan@zeroday.com"
  onCallSupport:
    - 1234567890
    - 0987654321
